/*
 * Made by Gabriel Barnard
 * Made on the 14th of April 2026
 */

// Preprocessor directive to protect against compilation in an incompatible C++ version (something lower than C++23)
#if __cplusplus < 202302L
#error "This error message is generated by a preprocessor directive. To compile this program, please use C++23 or greater. Some functions of this program cannot run on older C++ versions. On g++ and Clang, you can do this by using the following flag: -std=c++23"
#else

// Imports all necessary standard (std) C++ libraries
#include <cstdlib>
#include <unordered_map>
#include <set>
#include <string>
#include <iostream>
#include <vector>
#include <memory>
#include <fstream>
#include <cctype>
#include <limits>
#include <stdexcept>
#include <algorithm>
#include <ranges>
#include <filesystem>

class CSVprocessor {
    public:
        void menu(const std::string &csvPath);           // Menu for processing user input
    private:
        struct Course {                                  // Course object for storing course information from CSV file
            std::string number;
            std::string title;
            std::set<std::string> prerequisites;
        };
        std::unordered_map<std::string, Course> courses; // Hash table for storing Course objects

        // Loads and validates CSV file
        std::unordered_map<std::string, Course> processCSV(const std::string &csvPath);
        // Searches for a specific course in the hash table
        void searchCourse(const std::unordered_map<std::string, Course> &courses, const std::string &courseNumber);
        // Prints all courses in the hash table in alphanumerical order
        void printAllCourses(const std::unordered_map<std::string, Course> &courses);

        // Prompts the user to hit enter to continue and clears the screen
        void enterToContinue(void);
};


/*
 * processCSV(const std::string &csvPath)
 * O(n) time complexity
 * Loads data from CSV file "csvPath" into a hash table and ensures it doesn't have any formatting errors
 */
std::unordered_map<std::string, CSVprocessor::Course> CSVprocessor::processCSV(const std::string &csvPath) {
    // Opens an input file stream to the CSV file and verifies that it opened successfully
    std::ifstream inputStream;
    inputStream.open(csvPath);
    if (!inputStream.is_open()) {
        throw std::runtime_error("Error: Unable to open the CSV file \"" + csvPath + "\"");
    }

    std::string line;
    // Loops through all lines in the CSV file
    while (std::getline(inputStream, line)) {
        std::erase(line, '\r');                                                                                       // Removes the carriage return
        std::vector<std::string> parts = line | std::views::split(',') | std::ranges::to<std::vector<std::string>>(); // Splits the line by commas, and stores the parts in the "parts" vector

        CSVprocessor::Course course;

        // If there are less than two parts, an error is thrown
        if (parts.size() < 2) {
            throw std::runtime_error("Error: File formatted incorrectly.");
        }
        // Else if there are exactly two parts, the set's prerequisites become empty
        else if (parts.size() == 2) {
            course.prerequisites = {};
        }
        // Else if there are more than two parts, loops through the parts vector starting from the second index and inserts the individual parts
        else if (parts.size() > 2) {
            for (auto &part : parts | std::views::drop(2)) {
                if(!part.empty()) {                                                                   // Checks if the part isn't empty. This is done to prevent additional (unused) commas in the CSV from breaking the program
                    std::transform(part.begin(), part.end(), part.begin(), (int(*)(int))std::toupper); // Converts the part that'll be inserted to uppercase to prevent formatting issues
                    course.prerequisites.insert(part);
                }
            }
        }

        // Sets members of the course object to members of the parts vector
        course.number = parts[0];
        course.title = parts[1];

        // Converts the course number to upper case to prevent formatting issues
        std::transform(course.number.begin(), course.number.end(), course.number.begin(), (int(*)(int))std::toupper);

        // Adds the course object to the courses hash table with the course number as the key
        courses[course.number] = course;
    }

    inputStream.close();

    // Loops through the courses hash table, verifying that each courses's prerequisite has a matching course. If a course doesn't, an error is thrown
    for (const auto &[courseNumber, course] : courses) {
        for (const auto &prerequisite : course.prerequisites) {
            if (!courses.contains(prerequisite)) {
                throw std::runtime_error("Error: Invalid file format. Missing prerequisites.");
            }
        }
    }

    std::cout << '\n';
    std::cout << "CSV file \"" + csvPath + "\" loaded successfully." << '\n';
    std::cout << '\n';

    return courses;
}

/*
 * searchCourse(const std::unordered_map<std::string, CSVprocessor::Course> &courses, const std::string &courseNumber)
 * O(1) time complexity
 * Searches for a specific course "courseNumber" in the hash table "courses"
 */
void CSVprocessor::searchCourse(const std::unordered_map<std::string, CSVprocessor::Course> &courses, const std::string &courseNumber) {
    if (courses.contains(courseNumber)) {
        const Course &course = courses.at(courseNumber);

        std::cout << '\n';
        std::cout << "Course Info: " << course.number << " - "  << course.title << '\n';
        std::cout << "Course Prerequisites: ";
        if (course.prerequisites.empty()){
            std::cout << "None" << '\n';
        }
        else{
            // Loops through the prerequisites set, printing each individual prerequisite
            for (const auto &prerequisite : course.prerequisites) {
                std::cout << prerequisite;

                // If the prerequisite is not the last prerequisite in the set, adds a comma
                if (prerequisite != *course.prerequisites.rbegin()) {
                    std::cout << ", ";
                }
            }
            std::cout << '\n';
        }

        std::cout << '\n';

        return;
    }

    std::cout << '\n';
    std::cout << "Course not found. " << '\n';
    std::cout << '\n';
    return;
}

/*
 * printAllCourses(const std::unordered_map<std::string, CSVprocessor::Course> &courses)
 * O(n log n) time complexity
 * Prints all courses in hash table "courses" in alphanumerical order
 */
void CSVprocessor::printAllCourses(const std::unordered_map<std::string, CSVprocessor::Course> &courses) {
    std::vector<std::string> keys = courses | std::views::keys | std::ranges::to<std::vector<std::string>>(); // Extracts the keys from the courses hash table and places them in the keys vector
    std::sort(keys.begin(), keys.end());                                                                      // Sorts the keys vector alphanumerically

    // Loops through all keys in the keys vector
    for (const auto &key : keys) {
        const Course &course = courses.at(key); // Accesses the course associated with the current key

        std::cout << '\n';
        std::cout << "Course Info: " << course.number << " - "  << course.title << '\n';
        // NOTE: I have deliberately chosen not to display prerequisites because the sample program output (provided in the assignment description) only displays course numbers and titles, not the prerequisites.
    }

    std::cout << '\n';
}

/*
 * enterToContinue()
 * O(1) time complexity
 * prompts the user to "Press Enter to continue". Upon pressing enter, all text in the terminal is cleared.
 */
void CSVprocessor::enterToContinue(void) {
    std::cout << "Press ENTER to continue...";
    std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
    std::cin.get();
    std::cout << "\033[2J\033[H"; // Clears the screen
}

/*
 * menu(const std::string &csvPath)
 * O(n log n) worst-case time complexity
 * Displays a menu to a user, providing options to:
    * 1. Load CSV file "csvPath"
    * 2. Print all courses in csv file "csvPath" in alphanumeric order
    * 3. Print a specific course in the csv file "csvPath"
    * 9. Exit the program
 */
void CSVprocessor::menu(const std::string &csvPath) {
    std::cout << "\033[2J\033[H"; // Clears screen
    int choice{};

    // Loops while the user hasn't input 9 (9 means exit the program)
    while (choice != 9) {
        std::cout << "\033[1mOption 1:\033[0m Load the file data into the data structure." << '\n';
        std::cout << "\033[1mOption 2:\033[0m Print an alphanumerically ordered list of all the courses in the Computer Science department. Note that before you can print the course information or the sorted list of courses, you must load the data into the data structure." << '\n';
        std::cout << "\033[1mOption 3:\033[0m Print the course title and the prerequisites for any individual course." << '\n';
        std::cout << "\033[1mOption 9:\033[0m Exit the program." << '\n';
        std::cout << '\n';

        std::cout << "Choice: ";
        std::cin >> choice;
        // Protects against invalid user input, such as a user inputting a string instead of a number
        while (std::cin.fail()) {
            std::cin.clear();                                                   // Removes cin error state
            std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); // Discards invalid input until the next newline

            std::cout << '\n';
            std::cout << "You may only input the integers 1, 2, 3, or 9. Try again." << '\n';
            std::cout << '\n';
            std::cout << "Choice: ";
            std::cin >> choice;
        }

        // Prevents user from using option 2 or 3 if they haven't loaded a CSV file
        if (courses.empty() && choice != 1 && choice != 9) {
            std::cout << '\n';
            std::cout << "To use options 2 and 3, you must first load CSV data via option 1." << '\n';
            std::cout << '\n';
            enterToContinue();
            continue;
        }

        // Switches output depending on which option the user chose
        switch (choice){
            case 1:
                courses = processCSV(csvPath);
                enterToContinue();
                break;
            case 2:
                printAllCourses(courses);
                enterToContinue();

                break;
            case 3: {
                std::string courseNumber{};
                std::cout << "Input the course you would like to search for: ";
                std::cin >> courseNumber;                                                                                  // NOTE: A cin.fail() check isn't practically needed here because courseNumber is a string - strings will take almost anything
                std::transform(courseNumber.begin(), courseNumber.end(), courseNumber.begin(), (int(*)(int))std::toupper); // Converts the user's chosen course number to uppercase to prevent formatting issues

                searchCourse(courses, courseNumber);
                enterToContinue();

                break;
            }
            case 9:
                std::cout << "Exiting program." << '\n';
                std::cout << "\033[2J\033[H"; // Clears screen
                break;
            // Fallback for if the user inputs a invalid integer. I.e., an integer that is not 1, 2, 3 or 9
            default:
                std::cout << '\n';
                std::cout << "Your input must be the number 1, 2, 3, or 9. Any other input is invalid." << '\n';
                std::cout << '\n';

                enterToContinue();

                break;
        }
    }
}

int main(void) {
    std::string csvPath;
    std::cout << "Please enter the file name that contains the course data: ";
    std::getline(std::cin, csvPath);

    // Guards against invalid filepaths. Prompts the user to try again if the file path is invalid.
    while (std::filesystem::path(csvPath).extension() != ".csv" || !std::filesystem::exists(csvPath)) { // NOTE: A cin.fail() check isn't practically needed here because csvPath is a string. Strings will take almost anything.
        std::cout << '\n';
        std::cout << "Your chosen file name was invalid. Please try again: ";
        std::getline(std::cin, csvPath);
    }

    auto csvProcessor = std::make_unique<CSVprocessor>(); // Creates unique pointer to CSVprocessor class

    csvProcessor->menu(csvPath);

    return EXIT_SUCCESS;
}

// Closes the C++ version check
#endif
